openapi: '3.0.3'
info:
  title: 'Шесть городов API'
  description: >
    REST API для сервиса «Шесть городов» по аренде жилья.
    Сервис позволяет создавать, редактировать, удалять предложения по аренде,
    просматривать списки предложений, добавлять комментарии, регистрировать пользователей
    и осуществлять аутентификацию.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: '1.0.0'

paths:
  /offers:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOffer'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '400':
          description: Bad Request
      tags:
        - Offers
    get:
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
        - name: skip
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
      tags:
        - Offers
  /offers/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferDetails'
      tags:
        - Offers
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutOffer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OfferDetails'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '400':
          description: Bad Request
      tags:
        - Offers
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '400':
          description: Bad Request
      tags:
        - Offers
  /offers/premium/{city}:
    get:
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
      tags:
        - Premium Offers
  /offers/favorite:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Offer'
        '401':
          description: Unauthorized
      tags:
        - Favorite Offers
  /offers/favorite/{id}:
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
      tags:
        - Favorite Offers
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
      tags:
        - Favorite Offers
  /offers/{id}/comments:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
      tags:
        - Comments
    post:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateComment'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '400':
          description: Bad Request
      tags:
        - Comments
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          description: Forbidden
        '400':
          description: Bad Request
      tags:
        - Users
  /login:
    post:
      responses:
        '201':
          description: Created
        '401':
          description: Unauthorized
      tags:
        - Users
  /logout:
    delete:
      parameters:
        - name: X-Token
          in: header
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
      tags:
        - Users
  /check-session:
    get:
      parameters:
        - name: X-Token
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - Users

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
        - password
        - userType
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 15
        email:
          type: string
          format: email
        avatarUrl:
          type: string
        userType:
          type: string
          enum:
            - Basic
            - Pro
    CreateUser:
      type: object
      required:
        - name
        - email
        - password
        - userType
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 15
        email:
          type: string
          format: email
        avatarUrl:
          type: string
        password:
          type: string
          minLength: 6
          maxLength: 12
        userType:
          type: string
          enum:
            - Basic
            - Pro
    Comment:
      type: object
      required:
        - text
        - createdAt
        - rating
        - author_id
      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
        createdAt:
          type: string
          format: date-time
        rating:
          type: number
          minimum: 0
          maximum: 5
        author_id:
          type: integer
          minimum: 0
    CreateComment:
      type: object
      required:
        - text
        - rating
        - author_id
      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
        rating:
          type: number
          minimum: 0
          maximum: 5
        author_id:
          type: integer
          minimum: 0
    Offer:
      type: object
      required:
        - id
        - name
        - publicationDate
        - city
        - previewUrl
        - isPremium
        - isFavorite
        - rating
        - housingType
        - cost
        - commentsNumber
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 10
          maxLength: 100
        publicationDate:
          type: string
          format: date-time
        city:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
        previewUrl:
          type: string
          format: uri
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
          minimum: 0
          maximum: 5
        housingType:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
        cost:
          type: number
          minimum: 100
          maximum: 100000
        commentsNumber:
          type: integer
          minimum: 0
    OfferDetails:
      type: object
      required:
        - id
        - name
        - description
        - publicationDate
        - city
        - previewUrl
        - imagesUrls
        - isPremium
        - isFavorite
        - rating
        - housingType
        - roomsNumber
        - guestsNumber
        - cost
        - conveniences
        - author_id
        - commentsNumber
        - latitude
        - longitude
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        publicationDate:
          type: string
          format: date-time
        city:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
        previewUrl:
          type: string
          format: uri
        imagesUrls:
          type: array
          minLength: 6
          maxLength: 6
          items:
            type: string
            format: uri
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
          minimum: 0
          maximum: 5
        housingType:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
        roomsNumber:
          type: integer
          minimum: 1
          maximum: 8
        guestsNumber:
          type: integer
          minimum: 1
          maximum: 10
        cost:
          type: number
          minimum: 100
          maximum: 100000
        conveniences:
          type: array
          items:
            type: string
            enum:
              - Breakfast
              - Air conditioning
              - Laptop friendly workspace
              - Baby seat
              - Washer
              - Towels
              - Fridge
        author_id:
          type: integer
          minimum: 0
        latitude:
          type: number
          minimum: -90
          maximum: 90
        longitude:
          type: number
          minimum: -180
          maximum: 180
        commentsNumber:
          type: integer
          minimum: 0
    CreateOffer:
      type: object
      required:
        - name
        - description
        - city
        - previewUrl
        - imagesUrls
        - isPremium
        - housingType
        - roomsNumber
        - guestsNumber
        - cost
        - conveniences
        - author_id
        - latitude
        - longitude
      properties:
        name:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
        previewUrl:
          type: string
          format: uri
        imagesUrls:
          type: array
          minLength: 6
          maxLength: 6
          items:
            type: string
            format: uri
        isPremium:
          type: boolean
        housingType:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
        roomsNumber:
          type: integer
          minimum: 1
          maximum: 8
        guestsNumber:
          type: integer
          minimum: 1
          maximum: 10
        cost:
          type: number
          minimum: 100
          maximum: 100000
        conveniences:
          type: array
          items:
            type: string
            enum:
              - Breakfast
              - Air conditioning
              - Laptop friendly workspace
              - Baby seat
              - Washer
              - Towels
              - Fridge
        author_id:
          type: integer
          minimum: 0
        latitude:
          type: number
          minimum: -90
          maximum: 90
        longitude:
          type: number
          minimum: -180
          maximum: 180
    PutOffer:
      type: object
      required:
        - name
        - description
        - city
        - previewUrl
        - imagesUrls
        - isPremium
        - housingType
        - roomsNumber
        - guestsNumber
        - cost
        - conveniences
        - author_id
        - latitude
        - longitude
      properties:
        name:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          type: string
          enum:
            - Paris
            - Cologne
            - Brussels
            - Amsterdam
            - Hamburg
            - Dusseldorf
        previewUrl:
          type: string
          format: uri
        imagesUrls:
          type: array
          minLength: 6
          maxLength: 6
          items:
            type: string
            format: uri
        isPremium:
          type: boolean
        housingType:
          type: string
          enum:
            - apartment
            - house
            - room
            - hotel
        roomsNumber:
          type: integer
          minimum: 1
          maximum: 8
        guestsNumber:
          type: integer
          minimum: 1
          maximum: 10
        cost:
          type: number
          minimum: 100
          maximum: 100000
        conveniences:
          type: array
          items:
            type: string
            enum:
              - Breakfast
              - Air conditioning
              - Laptop friendly workspace
              - Baby seat
              - Washer
              - Towels
              - Fridge
        author_id:
          type: integer
          minimum: 0
        latitude:
          type: number
          minimum: -90
          maximum: 90
        longitude:
          type: number
          minimum: -180
          maximum: 180
